package chihalu.mina.horror.client.render;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.function.Consumer;
import java.util.zip.GZIPInputStream;
import net.minecraft.util.Mth;
import org.joml.Vector3f;
import org.joml.Vector3fc;

/**
 * Quad mesh of the flying broom, generated by tools/generate_broom.py (broom.bin). Positions are in blocks with the
 * seat on the handle's axis at the origin and the front towards +z. The lantern, its flame and its glass hang from
 * {@link #pivot()} so they can swing apart from the broom, and the bristles can be streamed back
 * ({@link #renderBristles}).
 */
public final class BroomMesh {
	private static final int MAGIC = 0x42524F4D;
	private static final int FLOATS = 8;
	public static final int SOLID = 0;
	public static final int LANTERN = 1;
	public static final int FLAME = 2;
	public static final int GLASS = 3;
	public static final int BRISTLE = 4;
	/** z of the bristles' roots at the back of the cuff, and about how far back they reach. */
	private static final float ROOT_Z = -0.63F;
	private static final float BRISTLE_LENGTH = 0.75F;
	/** Vertex colour of lit parts: alpha 254 tells the MinaRealism shader pack to draw them as emissive. */
	public static final int GLOW_MARKER = 0xFEFFFFFF;
	private static BroomMesh instance;

	private final Vector3f pivot;
	private final float[][] groups = new float[5][];

	private BroomMesh(final DataInputStream in) throws IOException {
		if (in.readInt() != MAGIC) {
			throw new IOException("Not a broom mesh");
		}

		this.pivot = new Vector3f(in.readFloat(), in.readFloat(), in.readFloat());
		for (int group = 0; group < this.groups.length; group++) {
			float[] data = new float[in.readInt() * 4 * FLOATS];
			for (int i = 0; i < data.length; i++) {
				data[i] = in.readFloat();
			}

			this.groups[group] = data;
		}
	}

	public static BroomMesh get() {
		if (instance == null) {
			String path = "/assets/mina-horror/models/entity/broom.bin";
			try (InputStream raw = BroomMesh.class.getResourceAsStream(path)) {
				if (raw == null) {
					throw new IOException("Missing " + path);
				}

				instance = new BroomMesh(new DataInputStream(new BufferedInputStream(new GZIPInputStream(raw))));
			} catch (IOException e) {
				throw new IllegalStateException("Failed to load broom mesh", e);
			}
		}

		return instance;
	}

	/** The lantern's hook, the point it swings about. */
	public Vector3fc pivot() {
		return this.pivot;
	}

	/** Emits one group; glowing parts are marked for the shader pack. */
	public void render(final PoseStack.Pose pose, final VertexConsumer buffer, final int group, final int light, final int overlay) {
		float[] data = this.groups[group];
		int color = group == FLAME || group == GLASS ? GLOW_MARKER : -1;
		for (int i = 0; i < data.length; i += FLOATS) {
			buffer.addVertex(pose, data[i], data[i + 1], data[i + 2])
				.setColor(color)
				.setUv(data[i + 6], data[i + 7])
				.setOverlay(overlay)
				.setLight(light)
				.setNormal(pose, data[i + 3], data[i + 4], data[i + 5]);
		}
	}

	/**
	 * Emits the bristles swept back by the wind of flight: stream 0 leaves them as modelled, 1 stretches the fan,
	 * gathers it towards the axis, lifts the droop and sets the tips fluttering.
	 */
	public void renderBristles(
		final PoseStack.Pose pose, final VertexConsumer buffer, final float stream, final float ageInTicks, final int light, final int overlay
	) {
		if (stream < 0.01F) {
			this.render(pose, buffer, BRISTLE, light, overlay);
			return;
		}

		float[] data = this.groups[BRISTLE];
		for (int i = 0; i < data.length; i += FLOATS) {
			float x = data[i];
			float y = data[i + 1];
			float z = data[i + 2];
			if (z < ROOT_Z) {
				float t = Math.min((ROOT_Z - z) / BRISTLE_LENGTH, 1.0F);
				float gather = 1.0F - 0.35F * stream * t;
				z = ROOT_Z - (ROOT_Z - z) * (1.0F + 0.12F * stream);
				x = x * gather + Mth.sin(ageInTicks * 1.7F + z * 9.0F) * 0.012F * stream * t;
				y = y * gather + 0.07F * stream * t * t + Mth.cos(ageInTicks * 1.3F + z * 7.0F) * 0.01F * stream * t;
			}

			buffer.addVertex(pose, x, y, z)
				.setColor(-1)
				.setUv(data[i + 6], data[i + 7])
				.setOverlay(overlay)
				.setLight(light)
				.setNormal(pose, data[i + 3], data[i + 4], data[i + 5]);
		}
	}

	/** Corners of the bounding box. */
	public void getExtents(final Consumer<Vector3f> output) {
		Vector3f min = new Vector3f(Float.POSITIVE_INFINITY);
		Vector3f max = new Vector3f(Float.NEGATIVE_INFINITY);
		Vector3f p = new Vector3f();
		for (float[] data : this.groups) {
			for (int i = 0; i < data.length; i += FLOATS) {
				p.set(data[i], data[i + 1], data[i + 2]);
				min.min(p);
				max.max(p);
			}
		}

		for (int corner = 0; corner < 8; corner++) {
			output.accept(new Vector3f(
				(corner & 1) == 0 ? min.x : max.x,
				(corner & 2) == 0 ? min.y : max.y,
				(corner & 4) == 0 ? min.z : max.z
			));
		}
	}
}
