package chihalu.mina.horror.client.render;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.function.Consumer;
import java.util.zip.GZIPInputStream;
import org.joml.Vector3f;
import org.joml.Vector3fc;

/**
 * Quad mesh of the flashlight, generated by tools/generate_flashlight.py (flashlight.bin). Positions are in item model
 * space (blocks, head towards -z). Parts are split into groups so the reflector, LED and lens can be drawn lit.
 */
public final class FlashlightMesh {
	private static final int MAGIC = 0x464C5348;
	private static final int FLOATS = 10;
	public static final int SOLID = 0;
	public static final int GLOW = 1;
	public static final int GLASS = 2;
	/** Vertex colour of lit parts: alpha 254 tells the MinaRealism shader pack to draw them as emissive. */
	public static final int GLOW_MARKER = 0xFEFFFFFF;
	private static FlashlightMesh instance;

	private final float[][] groups = new float[3][];

	private FlashlightMesh(final DataInputStream in) throws IOException {
		if (in.readInt() != MAGIC) {
			throw new IOException("Not a flashlight mesh");
		}

		for (int group = 0; group < this.groups.length; group++) {
			float[] data = new float[in.readInt() * 4 * FLOATS];
			for (int i = 0; i < data.length; i++) {
				data[i] = in.readFloat();
			}

			this.groups[group] = data;
		}
	}

	public static FlashlightMesh get() {
		if (instance == null) {
			String path = "/assets/mina-horror/models/item/flashlight.bin";
			try (InputStream raw = FlashlightMesh.class.getResourceAsStream(path)) {
				if (raw == null) {
					throw new IOException("Missing " + path);
				}

				instance = new FlashlightMesh(new DataInputStream(new BufferedInputStream(new GZIPInputStream(raw))));
			} catch (IOException e) {
				throw new IllegalStateException("Failed to load flashlight mesh", e);
			}
		}

		return instance;
	}

	/** Emits one group; lit picks the switched-on texture coordinates and marks the vertices as glowing. */
	public void render(final PoseStack.Pose pose, final VertexConsumer buffer, final int group, final boolean lit, final int light, final int overlay) {
		float[] data = this.groups[group];
		int uv = lit ? 8 : 6;
		int color = lit && group != SOLID ? GLOW_MARKER : -1;
		for (int i = 0; i < data.length; i += FLOATS) {
			buffer.addVertex(pose, data[i], data[i + 1], data[i + 2])
				.setColor(color)
				.setUv(data[i + uv], data[i + uv + 1])
				.setOverlay(overlay)
				.setLight(light)
				.setNormal(pose, data[i + 3], data[i + 4], data[i + 5]);
		}
	}

	/** Corners of the bounding box, for fitting the item into GUI slots. */
	public void getExtents(final Consumer<Vector3fc> output) {
		Vector3f min = new Vector3f(Float.POSITIVE_INFINITY);
		Vector3f max = new Vector3f(Float.NEGATIVE_INFINITY);
		Vector3f p = new Vector3f();
		for (float[] data : this.groups) {
			for (int i = 0; i < data.length; i += FLOATS) {
				p.set(data[i], data[i + 1], data[i + 2]);
				min.min(p);
				max.max(p);
			}
		}

		for (int corner = 0; corner < 8; corner++) {
			output.accept(new Vector3f(
				(corner & 1) == 0 ? min.x : max.x,
				(corner & 2) == 0 ? min.y : max.y,
				(corner & 4) == 0 ? min.z : max.z
			));
		}
	}
}
